/* Generated by bin2c, do not edit manually */
#ifndef __Gizmo_h_included
#define __Gizmo_h_included

/* Contents of file Gizmo.jpg */
extern const long int Gizmo_jpg_size;
extern const unsigned char Gizmo_jpg[32357];

#endif    /* __Gizmo_h_included */
