/* Generated by bin2c, do not edit manually */
#ifndef __hiro_h_included
#define __hiro_h_included

/* Contents of file hiro.jpg */
extern const long int hiro_jpg_size;
extern const unsigned char hiro_jpg[17231];

#endif    /* __hiro_h_included */
