/* Generated by bin2c, do not edit manually */
#ifndef __lilly_h_included
#define __lilly_h_included

/* Contents of file lilly.jpg */
extern const long int lilly_jpg_size;
extern const unsigned char lilly_jpg[15970];

#endif    /* __lilly_h_included */
