/* Generated by bin2c, do not edit manually */
#ifndef __Lucy_h_included
#define __Lucy_h_included

/* Contents of file Lucy.jpg */
extern const long int Lucy_jpg_size;
extern const unsigned char Lucy_jpg[33755];

#endif    /* __Lucy_h_included */
