/* Generated by bin2c, do not edit manually */
#ifndef __homer_h_included
#define __homer_h_included

/* Contents of file homer.gif */
extern const long int homer_gif_size;
extern const unsigned char homer_gif[199903];

#endif    /* __homer_h_included */
