/* Generated by bin2c, do not edit manually */
#ifndef __test2_h_included
#define __test2_h_included

/* Contents of file test2.gif */
extern const long int test2_gif_size;
extern const unsigned char test2_gif[44961];

#endif    /* __test2_h_included */
