/* Generated by bin2c, do not edit manually */
#ifndef __duck_hunt_h_included
#define __duck_hunt_h_included

/* Contents of file duck_hunt.gif */
extern const long int duck_hunt_gif_size;
extern const unsigned char duck_hunt_gif[141738];

#endif    /* __duck_hunt_h_included */
