/* Generated by bin2c, do not edit manually */
#ifndef __eye2_h_included
#define __eye2_h_included

/* Contents of file eye2.gif */
extern const long int eye2_gif_size;
extern const unsigned char eye2_gif[386815];

#endif    /* __eye2_h_included */
