/* Generated by bin2c, do not edit manually */
#ifndef __eyeball_h_included
#define __eyeball_h_included

/* Contents of file eyeball.gif */
extern const long int eyeball_gif_size;
extern const unsigned char eyeball_gif[516993];

#endif    /* __eyeball_h_included */
