/* Generated by bin2c, do not edit manually */
#ifndef __iron_man_h_included
#define __iron_man_h_included

/* Contents of file iron_man.gif */
extern const long int iron_man_gif_size;
extern const unsigned char iron_man_gif[967353];

#endif    /* __iron_man_h_included */
