/* Generated by bin2c, do not edit manually */
#ifndef __old_men_h_included
#define __old_men_h_included

/* Contents of file old_men.gif */
extern const long int old_men_gif_size;
extern const unsigned char old_men_gif[213506];

#endif    /* __old_men_h_included */
