/* Generated by bin2c, do not edit manually */
#ifndef __tank_h_included
#define __tank_h_included

/* Contents of file tank.gif */
extern const long int tank_gif_size;
extern const unsigned char tank_gif[167431];

#endif    /* __tank_h_included */
